'use client';
import {useEffect,useMemo,useState} from 'react';
import {BarChart3,Calculator,CircleDollarSign,FileText,Gauge,LayoutDashboard,Package,ReceiptText,Settings,ShieldCheck,Users,WalletCards,TrendingUp,Percent,Landmark,Scale,Building2,Layers,Bell,LogOut,Plus,Save,LoaderCircle} from 'lucide-react';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,BarChart,Bar} from 'recharts';
import {calculatePricing,breakEven,simpleEffectiveRate} from '@/lib/finance';
import {supabase} from '@/lib/supabase';

type Section='Visão Geral'|'Precificação'|'Produtos e Serviços'|'Custos Variáveis'|'Custos Fixos'|'Impostos'|'Regimes Tributários'|'DRE'|'Ponto de Equilíbrio'|'Canais de Venda'|'Simulador'|'Relatórios'|'Empresas'|'Usuários'|'Configurações'|'Auditoria';
const menu:[Section,any][]=[['Visão Geral',LayoutDashboard],['Precificação',Calculator],['Produtos e Serviços',Package],['Custos Variáveis',WalletCards],['Custos Fixos',Landmark],['Impostos',ReceiptText],['Regimes Tributários',Scale],['DRE',FileText],['Ponto de Equilíbrio',Gauge],['Canais de Venda',Layers],['Simulador',CircleDollarSign],['Relatórios',BarChart3],['Empresas',Building2],['Usuários',Users],['Configurações',Settings],['Auditoria',ShieldCheck]];
const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const chart=[{m:'Abr',r:62000,c:39100},{m:'Mai',r:68400,c:42500},{m:'Jun',r:71200,c:43700},{m:'Jul',r:76900,c:45800},{m:'Ago',r:81200,c:47800},{m:'Set',r:86400,c:49500}];

export default function Home(){
 const[session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[membership,setMembership]=useState<any>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadCompany();else setMembership(null)},[session]);
 async function loadCompany(){const{data}=await supabase.from('memberships').select('company_id,role,companies(id,name,legal_name,tax_id,state_code,city)').eq('user_id',session.user.id).limit(1);setMembership(data?.[0]||null)}
 if(loading)return <div className='centerPage'><LoaderCircle className='spin'/><b>Carregando...</b></div>;
 if(!session)return <Auth/>;
 if(!membership)return <Onboarding done={loadCompany}/>;
 return <Workspace session={session} membership={membership}/>;
}

function Auth(){
 const[mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:any){e.preventDefault();setBusy(true);setMsg('');if(mode==='signup'){const{error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});setMsg(error?.message||'Conta criada. Verifique seu e-mail caso a confirmação esteja ativa.')}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message)}setBusy(false)}
 return <div className='authPage'><div className='authIntro'><div className='brandIcon'><BarChart3/></div><h1>Margem de Contribuição</h1><p>Precificação, custos, lucro, DRE e tributação em um único SaaS.</p></div><form className='authCard' onSubmit={submit}><h2>{mode==='login'?'Entrar':'Criar conta'}</h2>{mode==='signup'&&<label>Nome<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>E-mail<input type='email' value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type='password' minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{msg&&<div className='msg'>{msg}</div>}<button className='submitBtn' disabled={busy}>{busy?'Processando...':mode==='login'?'Entrar':'Cadastrar'}</button><button type='button' className='linkBtn' onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Criar uma conta':'Já tenho conta'}</button></form></div>
}

function Onboarding({done}:{done:()=>void}){
 const[f,setF]=useState({name:'',legal_name:'',tax_id:'',state_code:'SC',city:''}),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:any){e.preventDefault();setBusy(true);const{error}=await supabase.rpc('create_company_with_admin',{p_name:f.name,p_legal_name:f.legal_name||null,p_tax_id:f.tax_id||null,p_state_code:f.state_code||null,p_city:f.city||null});if(error)setErr(error.message);else await done();setBusy(false)}
 return <div className='authPage'><div className='authIntro'><Building2 size={44}/><h1>Configure sua empresa</h1><p>Os dados são separados por empresa com RLS no banco.</p></div><form className='authCard' onSubmit={submit}><h2>Cadastro inicial</h2>{[['name','Nome da empresa'],['legal_name','Razão social'],['tax_id','CNPJ/CPF'],['state_code','UF'],['city','Cidade']].map(([k,l])=><label key={k}>{l}<input value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})} required={k==='name'}/></label>)}{err&&<div className='msg'>{err}</div>}<button className='submitBtn' disabled={busy}>{busy?'Criando...':'Criar empresa'}</button></form></div>
}

function Workspace({session,membership}:{session:any,membership:any}){
 const[section,setSection]=useState<Section>('Visão Geral'),[products,setProducts]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]);
 const companyId=membership.company_id,company:any=membership.companies;
 const[calc,setCalc]=useState<any>({baseCost:4.5,inboundFreight:.35,packaging:.5,personalization:1.8,directLabor:1.2,laborBurden:.3,variableEnergy:.15,lossPct:4,setupCost:30,quantity:100,salesTaxPct:6.5,cardPct:3.5,commissionPct:5,marketplacePct:0,fixedCostAllocationPct:15,desiredMarginPct:20});
 const result:any=useMemo(()=>calculatePricing(calc),[calc]),be=breakEven(18000,result.ok?result.contributionPct:0),eff=simpleEffectiveRate(480000,9.5,13860);
 useEffect(()=>{loadProducts();loadAudit()},[companyId]);
 async function loadProducts(){const{data}=await supabase.from('products').select('*').eq('company_id',companyId).is('deleted_at',null).order('created_at',{ascending:false});setProducts(data||[])}
 async function loadAudit(){const{data}=await supabase.from('audit_logs').select('*').eq('company_id',companyId).order('created_at',{ascending:false}).limit(50);setAudit(data||[])}
 async function savePricing(){const{data:s,error}=await supabase.from('pricing_scenarios').insert({company_id:companyId,name:'Simulação '+new Date().toLocaleString('pt-BR'),input_data:calc,created_by:session.user.id}).select().single();if(error)return alert(error.message);const{error:r}=await supabase.from('pricing_results').insert({company_id:companyId,scenario_id:s.id,result_data:result,calculation_memory:result.memory||[]});alert(r?r.message:'Precificação salva com sucesso.');loadAudit()}
 const update=(k:string,v:string)=>setCalc((x:any)=>({...x,[k]:Number(v)}));
 return <div className='shell'><aside className='sidebar'><div className='brand'><div className='brandIcon'><BarChart3 size={22}/></div><div><b>Margem</b><span>Contribuição</span></div></div><nav>{menu.map(([label,Icon])=><button key={label} className={section===label?'nav active':'nav'} onClick={()=>setSection(label)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className='sidebarFoot'><ShieldCheck size={17}/><div><b>Banco conectado</b><span>RLS multiempresa ativo</span></div></div></aside><main><header className='top'><div><h1>{section}</h1><p>{company?.name} · financeiro, custos e tributação</p></div><div className='topActions'><button className='iconBtn'><Bell size={18}/></button><div className='profile'><div className='avatar'>{(session.user.email||'U').slice(0,2).toUpperCase()}</div><div><b>{company?.name}</b><span>{membership.role}</span></div></div><button className='iconBtn' onClick={()=>supabase.auth.signOut()}><LogOut size={17}/></button></div></header><section className='content'>
 {section==='Visão Geral'&&<Dashboard products={products} result={result} be={be}/>}
 {section==='Precificação'&&<Pricing calc={calc} update={update} result={result} save={savePricing}/>}
 {section==='Produtos e Serviços'&&<Products companyId={companyId} products={products} reload={loadProducts}/>}
 {section==='Impostos'&&<Taxes eff={eff}/>}
 {section==='Regimes Tributários'&&<Regimes/>}
 {section==='Ponto de Equilíbrio'&&<BreakEven contribution={result.ok?result.contributionPct:0} be={be}/>}
 {section==='DRE'&&<Dre/>}
 {section==='Simulador'&&<Simulator calc={calc} update={update} result={result}/>}
 {section==='Auditoria'&&<Audit rows={audit}/>}
 {['Custos Variáveis','Custos Fixos','Canais de Venda','Relatórios','Empresas','Usuários','Configurações'].includes(section)&&<Generic title={section}/>}
 </section></main></div>
}

function Kpi({title,value,sub,icon:Icon}:{title:string,value:string,sub:string,icon:any}){return <div className='card kpi'><div><span>{title}</span><strong>{value}</strong><small>{sub}</small></div><div className='kpiIcon'><Icon size={21}/></div></div>}
function Dashboard({products,result,be}:{products:any[],result:any,be:number|null}){return <><div className='hero'><div><span>Diagnóstico financeiro</span><h2>Visão consolidada</h2><p>Os produtos já são carregados do novo banco Supabase exclusivo do SaaS.</p></div></div><div className='kpis'><Kpi title='Produtos cadastrados' value={String(products.length)} sub='dados reais' icon={Package}/><Kpi title='Margem da simulação' value={result.ok?result.contributionPct+'%':'—'} sub={result.ok?brl(result.contribution):'—'} icon={Percent}/><Kpi title='Lucro unitário' value={result.ok?brl(result.profit):'—'} sub={result.ok?result.profitPct+'%':'—'} icon={CircleDollarSign}/><Kpi title='Ponto de equilíbrio' value={brl(be||0)} sub='base de referência' icon={Gauge}/></div><div className='card'><div className='cardTitle'><div><b>Receita x custos</b><span>Exemplo visual até alimentar a DRE real</span></div></div><ResponsiveContainer width='100%' height={320}><AreaChart data={chart}><CartesianGrid stroke='#edf2f7' vertical={false}/><XAxis dataKey='m'/><YAxis/><Tooltip/><Area dataKey='r' stroke='#0f66e8' fill='#dcecff'/><Area dataKey='c' stroke='#76a8ef' fill='none'/></AreaChart></ResponsiveContainer></div></>}
function Pricing({calc,update,result,save}:{calc:any,update:any,result:any,save:()=>void}){const fields=[['baseCost','Custo do produto'],['inboundFreight','Frete entrada'],['packaging','Embalagem'],['personalization','Personalização'],['directLabor','Mão de obra'],['laborBurden','Encargos'],['variableEnergy','Energia variável'],['setupCost','Setup'],['quantity','Quantidade'],['lossPct','Perdas %'],['salesTaxPct','Imposto venda %'],['cardPct','Cartão %'],['commissionPct','Comissão %'],['marketplacePct','Marketplace %'],['fixedCostAllocationPct','Custos fixos %'],['desiredMarginPct','Lucro desejado %']];return <div className='pricingLayout'><div className='card'><div className='cardTitle'><div><b>Formação do preço</b><span>Parâmetros ajustáveis</span></div><button className='blueBtn' onClick={save}><Save size={15}/>Salvar</button></div><div className='formGrid'>{fields.map(([k,l])=><label key={k}><span>{l}</span><input type='number' step='.01' value={calc[k]} onChange={e=>update(k,e.target.value)}/></label>)}</div></div><div className='card sticky'>{result.ok?<><div className='resultMain'><span>Preço recomendado</span><strong>{brl(result.price)}</strong></div><div className='resultRows'><p><span>Custo-base</span><b>{brl(result.costBase)}</b></p><p><span>Margem contribuição</span><b>{brl(result.contribution)} · {result.contributionPct}%</b></p><p><span>Lucro</span><b>{brl(result.profit)} · {result.profitPct}%</b></p><p><span>Preço mínimo</span><b>{brl(result.minPrice)}</b></p><p><span>Desconto máximo</span><b>{result.maxDiscountPct}%</b></p></div><details><summary>Como foi calculado?</summary>{result.memory.map((x:string)=><p key={x}>{x}</p>)}</details></>:<div>{result.error}</div>}</div></div>}
function Products({companyId,products,reload}:{companyId:string,products:any[],reload:()=>void}){const[f,setF]=useState({name:'',sku:'',base_cost:'',sale_price:''});async function add(e:any){e.preventDefault();const{error}=await supabase.from('products').insert({company_id:companyId,name:f.name,sku:f.sku||null,base_cost:Number(f.base_cost||0),sale_price:Number(f.sale_price||0)});if(error)alert(error.message);else{setF({name:'',sku:'',base_cost:'',sale_price:''});reload()}}return <><form className='card inlineForm' onSubmit={add}><b>Novo produto</b><input placeholder='Nome' value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><input placeholder='SKU' value={f.sku} onChange={e=>setF({...f,sku:e.target.value})}/><input placeholder='Custo' type='number' step='.01' value={f.base_cost} onChange={e=>setF({...f,base_cost:e.target.value})}/><input placeholder='Preço' type='number' step='.01' value={f.sale_price} onChange={e=>setF({...f,sale_price:e.target.value})}/><button className='blueBtn'><Plus size={15}/>Adicionar</button></form><div className='card tableCard'><table><thead><tr><th>Produto</th><th>SKU</th><th>Custo</th><th>Preço</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.sku||'—'}</td><td>{brl(Number(p.base_cost||0))}</td><td>{p.sale_price==null?'—':brl(Number(p.sale_price))}</td></tr>)}</tbody></table></div></>}
function Taxes({eff}:{eff:number}){return <><div className='hero'><div><span>Tributação parametrizável</span><h2>Impostos com vigência</h2><p>Regras específicas devem considerar CNAE, NCM, UF, município e natureza da operação.</p></div></div><div className='kpis'><Kpi title='Simples efetivo' value={eff+'%'} sub='exemplo de fórmula' icon={Percent}/><Kpi title='IBS teste 2026' value='0,10%' sub='não custo automático' icon={ReceiptText}/><Kpi title='CBS teste 2026' value='0,90%' sub='não custo automático' icon={ReceiptText}/><Kpi title='Regras' value='Versionadas' sub='por vigência' icon={Scale}/></div></>}
function Regimes(){return <div className='cards4'>{['MEI','Simples Nacional','Lucro Presumido','Lucro Real','Lucro Arbitrado'].map(x=><div className='card' key={x}><Scale/><h3>{x}</h3><p>Estrutura criada no banco com regras versionáveis.</p></div>)}</div>}
function BreakEven({contribution,be}:{contribution:number,be:number|null}){const data=[{x:'Faturamento',v:86400},{x:'Equilíbrio',v:be||0},{x:'Meta',v:102000}];return <><div className='kpis'><Kpi title='Custos fixos base' value={brl(18000)} sub='referência' icon={Landmark}/><Kpi title='MC atual' value={contribution+'%'} sub='simulação' icon={Percent}/><Kpi title='Equilíbrio' value={brl(be||0)} sub='fixos ÷ MC%' icon={Gauge}/><Kpi title='Segurança' value={be?(((86400-be)/86400)*100).toFixed(1)+'%':'—'} sub='folga' icon={TrendingUp}/></div><div className='card'><ResponsiveContainer width='100%' height={300}><BarChart data={data}><XAxis dataKey='x'/><YAxis/><Tooltip/><Bar dataKey='v' fill='#0f66e8'/></BarChart></ResponsiveContainer></div></>}
function Dre(){const rows=[['Receita bruta',86400],['Impostos',-5616],['Receita líquida',80784],['Custos variáveis',-34600],['Margem contribuição',46184],['Custos fixos',-18000],['EBITDA gerencial',28184]];return <div className='card tableCard'><table><tbody>{rows.map(([n,v]:any)=><tr key={n}><td>{n}</td><td>{brl(v)}</td></tr>)}</tbody></table></div>}
function Simulator({calc,update,result}:{calc:any,update:any,result:any}){return <div className='pricingLayout'><div className='card'><div className='formGrid'><label><span>Quantidade</span><select value={calc.quantity} onChange={e=>update('quantity',e.target.value)}>{[10,25,50,100,300,500,1000].map(q=><option key={q}>{q}</option>)}</select></label><label><span>Técnica</span><select><option>UV</option><option>Silk</option><option>Sublimação</option><option>Laser</option><option>Transfer</option></select></label></div></div><div className='card'><div className='resultMain'><span>Preço unitário</span><strong>{result.ok?brl(result.price):'—'}</strong></div></div></div>}
function Audit({rows}:{rows:any[]}){return <div className='card tableCard'><table><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>ID</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString('pt-BR')}</td><td>{r.action}</td><td>{r.entity_type}</td><td>{r.entity_id}</td></tr>)}</tbody></table></div>}
function Generic({title}:{title:string}){return <div className='hero'><div><span>Módulo conectado</span><h2>{title}</h2><p>A estrutura de banco, tenant e permissões já está preparada para este módulo.</p></div></div>}
